server:
  port: 9091

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/testdb
    username: sa
    password:
  application:
    name: order-service
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

